name: Deploy to WP Engine

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v2

    - name: Get PR Labels
      id: pr-labels
      uses: jimschubert/query-github-action@v1
      with:
        query: ${{ github.event.pull_request.url }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for Deployment Label
      id: check-label
      run: |
        DEPLOY_LABEL="deploy"
        PR_LABELS="${{ steps.pr-labels.outputs.data }}"
        if echo "$PR_LABELS" | grep -q "\"name\": \"$DEPLOY_LABEL\""; then
          echo "Deployment label found."
          echo "DO_DEPLOY=true" >> $GITHUB_ENV
        else
          echo "Deployment label not found."
          echo "DO_DEPLOY=false" >> $GITHUB_ENV

    - name: Set up Environment
      if: env.DO_DEPLOY == 'true'
      run: |
        if [[ "${{ github.base_ref }}" == "staging" ]]; then
          echo "WPE_ENV=ovhstaging" >> $GITHUB_ENV
        elif [[ "${{ github.base_ref }}" == "main" ]]; then
          echo "WPE_ENV=orchardvalleyh" >> $GITHUB_ENV

    - name: GitHub Action Deploy to WP Engine
      if: env.DO_DEPLOY == 'true'
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        WPE_ENV: ${{ env.WPE_ENV }}
        REMOTE_PATH: "wp-content/themes/ovh/"
        PHP_LINT: TRUE
        FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.deployignore
        CACHE_CLEAR: TRUE
